name: Docker

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Target to build'
        required: false
        type: choice
        options:
          - flakes
          - dockerfile
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker:
    uses: socheatsok78/uses/.github/workflows/docker-buildx-bake.yml@main
    permissions:
      contents: read
      packages: write
    with:
      targets: ${{ github.event.inputs.target || 'flakes' }}
      enable-dockerhub: ${{ github.event_name != 'pull_request' }}
      enable-ghcr: ${{ github.event_name != 'pull_request' }}
      permit-login: ${{ github.event_name != 'pull_request' }}
      permit-push: ${{ github.event_name != 'pull_request' }}
      permit-cache: ${{ github.event_name != 'pull_request' }}
      custom-cache-mode: max
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
